activity/urls.py
from django.urls import include, path
from .views import index, save_act, save_person

urlpatterns = [
    path('', index, name='index'),
    path('save_act', save_act, name='save_act'),
    path('save_person/<id>', save_person, name='save_person')
]

main/urls.py
from django.urls import path
from .views import home, details, logIn, logOut, register

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('details/', details, name='details'),
    path('login/', logIn, name='login'),
    path('logout/', logOut, name='logout'),
    path('register/', register, name='register'),
]

webpadli/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('activity/', include(('activity.urls', 'activity'), namespace='activity')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', include(('main.urls', 'main'), namespace='main')),
]

activity/models.py
from django.db import models

# Create your models here.
class Activity(models.Model):
    name = models.CharField(max_length=20, default="Your Activity")

class Person(models.Model):
    name = models.CharField(max_length=20, default="Your Name")
    activity = models.ManyToManyField(Activity)

main/models.py
from django.db import models

# Create your models here.

activity/forms.py
from django import forms
from .models import Activity, Person

class Form_Activity(forms.ModelForm):
	class Meta:
		model = Activity
		fields = ['name']
	error_messages = {
		'required' : 'Please Type'
	}
	input_nam = {
		'type' : 'text',
		'placeholder' : 'new activity'
	}
	name = forms.CharField(label='', required=True, max_length=100, widget=forms.TextInput(attrs=input_nam))

class Form_Person(forms.ModelForm):
	class Meta:
		model = Person
		fields = ['name']
	
	error_messages = {
		'required' : 'Please Type'
	}

	input_nam = {
		'type' : 'text',
		'placeholder' : 'add person'
	}
	name = forms.CharField(label='', required=True, max_length=100, widget=forms.TextInput(attrs=input_nam))

activity/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Form_Activity, Form_Person
from .models import Activity, Person

# Create your views here.
def index(request):
    act = Activity.objects.all()
    person = Person.objects.all()
    response = {'form_act' : Form_Activity, 'form_person' : Form_Person, 'activities' : act, 'persons' : person}
    return render(request, 'main/activity.html', response)

def save_act(request):
    form = Form_Activity(request.POST)
    if (request.method == 'POST' and form.is_valid):
        form.save()
    return HttpResponseRedirect('/activity')

def save_person(request, id):
    act = Activity.objects.get(id=id)
    form = Form_Person(request.POST)
    persons = Person.objects.all()
    if (request.method == 'POST' and form.is_valid()):
        name = form.cleaned_data['name']
        ada = False
        for person in persons:
            if person.name == name:
                person.activity.add(act)
                ada = True
        if not ada:
            new_person = Person(name=name)
            new_person.save()
            new_person.activity.add(act)
    return HttpResponseRedirect('/activity')

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

def home(request):
    return render(request, 'main/home.html')

def details(request):
    return render(request, 'main/details.html')

def logIn(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else :
            messages.error(request,'please enter the correct username and password')
    return render(request, 'main/login.html')

def logOut(request):
    logout(request)
    return redirect('/')

def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 == password2:
            if len(password1) < 8:
                messages.error(request, 'please enter the password at least 8 character')
            else:
                try:
                    user= User.objects.get(username=username)
                    messages.error(request,'username is already taken. please choose the other username')
                except User.DoesNotExist:
                    user = User.objects.create_user(username, password=password1)
                    user.save()
                    login(request, user)
                    messages.success(request, 'well done. your account is saved')
        else:
            messages.error(request, 'please enter the same password for both field')
    return render(request, 'main/register.html')

activity/templates/main/activity.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Activities</title>
<link rel="stylesheet" href="{% static 'activity.css' %}">
{% endblock meta %}

{% block content %}

<div id="titleAct">
    <p>
      My Activities
    </p>
    <img src="{% static 'activity.png' %}">
</div>

<div id="formAct">
    <form action="{% url 'activity:save_act' %}" method="POST">
        {% csrf_token %}
        {{ form_act }}
        <input type="submit" value="ADD">
    </form>
    <hr width="95%">
</div>

<div id="listAct">
    {% if activities %}
        <ol>
            {% for activity in activities %}
                <li class="act-name">
                    {{ activity.name }}
                </li>
                <ul>
                    {% for person in activity.person_set.all %}
                        <li>
                            {{ person.name }}
                        </li>
                    {% endfor %}
                </ul>
                <form action="{% url 'activity:save_person' id=activity.id %}" method="POST">
                    {% csrf_token %}
                    {{ form_person }}
                    <input type="submit" value="add">
                </form>
            {% endfor %}
        </ol>
    {% else %}
        <p>Nothing here</p>
    {% endif %}
</div>

{% endblock content %}