main/urls.py
from django.urls import path
from .views import home, details, logIn, logOut, register

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('details/', details, name='details'),
    path('login/', logIn, name='login'),
    path('logout/', logOut, name='logout'),
    path('register/', register, name='register'),
]

story1/urls.py
from django.urls import include, path
from .views import index

urlpatterns = [
    path('', index, name='index'),
]

webpadli/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('activity/', include(('activity.urls', 'activity'), namespace='activity')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', include(('main.urls', 'main'), namespace='main')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Nunito' rel='stylesheet'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-203798100-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-203798100-1');
</script>
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PLXNHXV');</script>
<!-- End Google Tag Manager -->
  {% block meta %}
  {% endblock meta %}
</head>

<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PLXNHXV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
</body>

<nav class="navbar navbar-expand-lg navbar-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:home' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'story1:index' %}">Old Page</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'main:details' %}">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'courses:index' %}">Courses</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'activity:index' %}">Activities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'catalog:index' %}">Catalog</a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      {% if not user.is_authenticated %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'main:login' %}">Log In</a>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link">
            Haloo {{ user.username }}
          </a>
        </li>
      </ul>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" id="logout" href="{% url 'main:logout' %}">Log Out</a>
        </li>
      </ul>
      {% endif %}
    </form>
  </div>
</nav>
  {% block content %}
  {% endblock content %}

  <footer class="page-footer font-small blue pt-4">
    <div>
      <a href="https://www.facebook.com/fadliaa68">
        <img src="{% static 'css/fb.png' %}" class="sosmed">
      </a>
      <a href="https://www.instagram.com/fadlia68">
        <img src="{% static 'css/ig.png' %}" class="sosmed">
      </a>
      <a href="https://id.linkedin.com/in/fadli-aulawi-9b4990148">
        <img src="{% static 'css/linked.png' %}" class="sosmed">
      </a>
    </div>

    <div class="footer-copyright text-center py-3">
        © 2020 Copyright
        <h6 id="dummy">Icons made by flaticon.com</h6>
    </div>      
  </footer>
</html>