main/urls.py
from django.urls import path
from .views import home, details, logIn, logOut, register

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('details/', details, name='details'),
    path('login/', logIn, name='login'),
    path('logout/', logOut, name='logout'),
    path('register/', register, name='register'),
]

webpadli/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('activity/', include(('activity.urls', 'activity'), namespace='activity')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', include(('main.urls', 'main'), namespace='main')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

def home(request):
    return render(request, 'main/home.html')

def details(request):
    return render(request, 'main/details.html')

def logIn(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else :
            messages.error(request,'please enter the correct username and password')
    return render(request, 'main/login.html')

def logOut(request):
    logout(request)
    return redirect('/')

def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 == password2:
            if len(password1) < 8:
                messages.error(request, 'please enter the password at least 8 character')
            else:
                try:
                    user= User.objects.get(username=username)
                    messages.error(request,'username is already taken. please choose the other username')
                except User.DoesNotExist:
                    user = User.objects.create_user(username, password=password1)
                    user.save()
                    login(request, user)
                    messages.success(request, 'well done. your account is saved')
        else:
            messages.error(request, 'please enter the same password for both field')
    return render(request, 'main/register.html')

main/templates/main/details.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Profile</title>
<link rel="stylesheet" href="{% static 'main.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>

{% endblock meta %}

{% block content %}
  <div id="titleDetail">
    <p>
      My Profile
    </p>
    <img src="{% static 'user.png' %}" id="user">
  </div>

  <div id="accDetail">
    <div>
      <button class="up">
        ^
      </button>
      <button class="accordion">
        
      </button>
      <button class="down">
        v
      </button>
    </div>
    <div class="isi" id="1">    

    </div>
    <div>
      <button class="up">
        ^
      </button>
      <button class="accordion">
        
      </button>
      <button class="down">
        v
      </button>
    </div>
    <div class="isi" id="2">    
      
    </div>
    <div>
      <button class="up">
        ^
      </button>
      <button class="accordion">
        
      </button>
      <button class="down">
        v
      </button>
    </div>
    <div class="isi" id="3">    
      
    </div>
    <div>
      <button class="up">
        ^
      </button>
      <button class="accordion">
        
      </button>
      <button class="down">
        v
      </button>
    </div>
    <div class="isi" id="4">    
      
    </div>

  </div>
  
  
  <div id="titleDetail">
    <p>
      My FAQ
    </p>
    <img src="{% static 'help.png' %}" id="help">
  </div>

  <div id="mainFAQ">      
    <br><br>    
    <h5>
      1. What is your hobby?
    </h5>
    <h6>
      Mostly enjoying me time, especially playing football game. 
      Sometimes like to do some exercise in programming course.
    </h6>
    <br>
    <h5>
      2. What is your most memorable moment in your life?
    </h5>
    <h6>
      So far, the whole of my high school years still be the most remarkable moment in my life.
    </h6>
    <br>
    <h5>
      3. What is your goals at the college?
    </h5>
    <h6>
      In 3-4 years, i want to make some project with my friends. 
      This project will focus on the needs of informatics students.
    </h6>
    <br>
    <h5>
      4. What will you do after graduate?
    </h5>
    <h6>
      After graduated, the first thing i do is to thank everyone who has supported me until that time comes.
    </h6>
    <br>
    <h5>
      5. What is your life motto?
    </h5>
    <h6>
      Life is Never Flat. 
      <br>It is too complicated for you, even in your best times.
      Just let it go and flow until it reaches the end of the story.
    </h6>
  </div>
  <div id="jeda">
  </div>
    <h5 id="question">
      Want to know more? Send your questions to fadliaulawia@gmail.com
    </h5>
  <hr>

  <script src="{% static 'main.js' %}" type="text/javascript"></script>

{% endblock content %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Web Padli</title>
<link rel="stylesheet" href="{% static 'main.css' %}">
{% endblock meta %}

{% block content %}

  <div class="row">
    <div class="jumbotron text-left col-md-4" id="jumbo1">
        <div class="container">
            <img src="{% static 'fadli.jpg' %}" alt="foto saya" class="responsive" id="foto-saya">
      </div>
  </div>

  <div class="jumbotron text-left col-md-8">
      <div class="col">
          <h1 id="hello">Hello!!!</h1>
          <br><br>
          <h2>Fadli Aulawi</h2>
          <h6>computer science student</h6>
          <br>
          <h5>A diligent person who likes to <br>
              discover everything in his world. <br>
              Now looking for a long term <br>
              scholarship and its kind.</h5>
          <p>
              <a class="btn btn-primary"  id="id-cv" href="{% static 'CV_Sep20.pdf' %}" role="button">My Resume</a>
          </p>
      </div>
  </div>
  </div>

  <div class="container">
  <div class="row">
  <div class="col-md-4">
    <h3>Skill</h3>
    <p class="sbe">
      Programming<br>Problem Solving<br>Time Management<br>Hard Work
    </p>
  </div>
  <div class="col-md-4">
    <h3>Biodata</h3>
    <p class="sbe">
      Fadli Aulawi Al Ghiffari<br>Bandung, West Java<br>19 years old<br>
      Computer Science<br>Universitas Indonesia<br>Love to Learn
    </p>
  </div>
  <div class="col-md-4">
    <h3>Experience</h3>
    <p class="sbe">Silver Informatics Medalist<br>Teaching Assistant<br>
      Quran Department<br>Baritone Player<br>
      <h2 id="inv">
        sjdhabucgfkybgfuy Fusce cursus commodo, tortor mauris condimentum nibh, 
      </h2>
    </p>
    <div id="button-more">
      <a class="btn btn-outline" href="{% url 'main:details' %}" role="button">
        more about me...
      </a>
    </div>
  </div> 
  </div>
  </div>
  <hr>

{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Log In</title>
<link rel="stylesheet" href="{% static 'main.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>

{% endblock meta %}

{% block content %}
  <div id="titleLogin">
    <p>
      Log In
    </p>
    <hr>
  </div>

<div id="formLogin">
    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <label for="username" style="padding-right: 5px;">Username</label> 
            <input type="text" name="username" required>
        </div>
        <div>
            <label for="password">Password</label> 
            <input type="password" name="password" required>
        </div>
        
        <div style="color: red;">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </div>
        <div style="margin: 20px;">
            <button type="submit" class="btn btn-outline-dark">Log In</button>
        </div>

        <div>
            <p>
                doesn't have an account? register <a href="{% url 'main:register' %}">here</a>
            </p>
        </div>

    </form>
  
</div>
{% endblock content %}

main/templates/main/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Register</title>
<link rel="stylesheet" href="{% static 'main.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"> </script>

{% endblock meta %}

{% block content %}
  <div id="titleLogin">
    <p>
      Register
    </p>
    <hr>
  </div>

<div id="formReg">
    <form method="POST">
    {% csrf_token %}
    <table id="tableReg">
        <tr>
            <td><label for="username">Username</label></td>
            <td>
                <input type="text" name="username" required>
            </td>
        </tr>
        <br>
        <tr>
            <td><label for="password1">Password</label></td>
            <td>
                <input type="password" name="password1" required> 
            </td>
        </tr>
        <br>
        <tr>
            <td><label for="password2">Password Again</label></td>
            <td>
                <input type="password" name="password2" required> 
            </td>
        </tr>
    </table>
        
    {% for message in messages %}
    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
    <div style="color: red;">
        {{ message }}
    </div> 
    {% else %}
    <div style="color: green;">
        {{ message }}
    </div>
    {% endif %}
    {% endfor %}
    <div style="margin: 10px;">
        <button type="submit" class="btn btn-outline-dark">Register</button>
    </div>

    <div>
        <p>
            already have an account? login <a href="{% url 'main:login' %}">here</a>
        </p>
    </div>

    </form>
  
</div>
{% endblock content %}