courses/urls.py
from django.urls import include, path
from .views import index, add, savename, delete, detail

urlpatterns = [
    path('', index, name='index'),
    path('add/', add, name='add'),
    path('add/savename', savename, name='savename'),
    path('delete/<id>', delete, name='delete'),
    path('detail/<id>', detail, name='detail')
]

main/urls.py
from django.urls import path
from .views import home, details, logIn, logOut, register

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('details/', details, name='details'),
    path('login/', logIn, name='login'),
    path('logout/', logOut, name='logout'),
    path('register/', register, name='register'),
]

webpadli/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('activity/', include(('activity.urls', 'activity'), namespace='activity')),
    path('catalog/', include(('catalog.urls', 'catalog'), namespace='catalog')),
    path('', include(('main.urls', 'main'), namespace='main')),
]

courses/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length=100, default='mata kuliah x')
    teacher = models.CharField(max_length=50, default='bapa/ibu dosen')
    credits = models.CharField(max_length=2, default='0')
    year = models.CharField(max_length=30, default='tahun ini')
    room = models.CharField(max_length=10, default='fasilkom')
    desc = models.CharField(max_length=200, default='seru parah')

main/models.py
from django.db import models

# Create your models here.

courses/forms.py
from django import forms
from .models import Course

class Input_Form(forms.ModelForm):
	class Meta:
		model = Course
		fields = ['name', 'teacher', 'credits', 'year', 'room', 'desc']
	error_messages = {
		'required' : 'Please Type'
	}
	input_nam = {
		'type' : 'text',
		'placeholder' : 'Ex: PePeWe'
	}
	input_tea = {
		'type' : 'text',
		'placeholder' : 'Mr/Ms'
	}
	input_cre = {
		'type' : 'text',
		'placeholder' : '1-6'
	}
	input_yea = {
		'type' : 'text',
		'placeholder' : '20xx / 20xx'
	}
	input_roo = {
		'type' : 'text',
		'placeholder' : 'Gmeet/zoom'
	}
	input_des = {
		'type' : 'text',
		'placeholder' : 'what is it'
	}
	name = forms.CharField(label='Name', required=True, max_length=100, widget=forms.TextInput(attrs=input_nam))
	teacher = forms.CharField(label='Teacher', required=True, max_length=50, widget=forms.TextInput(attrs=input_tea))
	credits = forms.CharField(label='Credits', required=True, max_length=2, widget=forms.TextInput(attrs=input_cre))
	year = forms.CharField(label='Year', required=True, max_length=30, widget=forms.TextInput(attrs=input_yea))
	room = forms.CharField(label='Room', required=True, max_length=10, widget=forms.TextInput(attrs=input_roo))
	desc = forms.CharField(label='Description', required=True, max_length=200, widget=forms.TextInput(attrs=input_des))

courses/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Input_Form
from .models import Course

def index(request):
    response = {}
    courses = Course.objects.all()
    response['courses'] = courses
    return render(request, 'main/courses.html', response)

def add(request):
    response = {'form' : Input_Form}
    return render(request, 'main/add.html', response)

def savename(request):
    form = Input_Form(request.POST)
    if (request.method == 'POST' and form.is_valid):
        form.save()
    return HttpResponseRedirect('/courses')

def detail(request, id):
    obj = Course.objects.get(id=id)
    response = {'course' : obj}
    return render(request, 'main/detail.html', response)

def delete(request, id):
    Course.objects.get(id=id).delete()
    return HttpResponseRedirect('/courses')

main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.utils.safestring import mark_safe
from django.contrib.auth.models import User

def home(request):
    return render(request, 'main/home.html')

def details(request):
    return render(request, 'main/details.html')

def logIn(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else :
            messages.error(request,'please enter the correct username and password')
    return render(request, 'main/login.html')

def logOut(request):
    logout(request)
    return redirect('/')

def register(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        if password1 == password2:
            if len(password1) < 8:
                messages.error(request, 'please enter the password at least 8 character')
            else:
                try:
                    user= User.objects.get(username=username)
                    messages.error(request,'username is already taken. please choose the other username')
                except User.DoesNotExist:
                    user = User.objects.create_user(username, password=password1)
                    user.save()
                    login(request, user)
                    messages.success(request, 'well done. your account is saved')
        else:
            messages.error(request, 'please enter the same password for both field')
    return render(request, 'main/register.html')

courses/templates/main/add.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Courses</title>
<link rel="stylesheet" href="{% static 'course.css' %}">
{% endblock meta %}

{% block content %}
  <div id="judulAdd">
    <p>
      Add Course
    </p>
    <img src="{% static 'course.png' %}" id="imgAdd">
  </div>
  <hr width="95%">
  
  <div id="formAdd">
    <form action="savename" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="ADD">
    </form>
  </div>

{% endblock content %}

courses/templates/main/courses.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Courses</title>
<link rel="stylesheet" href="{% static 'course.css' %}">
{% endblock meta %}

{% block content %}
  <div id="titleCourse">
    <p>
      My Courses
    </p>
    <img src="{% static 'course.png' %}">
  </div>

  <div id="addButton">
    <a href="{% url 'courses:add' %}">
      <button type="button" class="btn btn-outline-dark">Add Course</button>
    </a>
    <hr width="95%">
  </div>

  <div id="listCourse">
    {% if courses %}
    <table border="1" align="center">
        <tr>
          <td id="titleTable">Course</td>
          <td id="titleTable">Teacher</td>
        </tr>
      {% for course in courses %}
        <tr>
          <td> {{ course.name }} </td>
          <td> {{ course.teacher }} </td>
          <td> 
            <a href="{% url 'courses:detail' id=course.id %}">
              details
            </a>
          </td>
          <td>
            <a href="{% url 'courses:delete' id=course.id %}">
              delete
            </a>
          </td>
        </tr>
      {% endfor%}
    </table>
    {% else %}
    <p id="nothingHere">
      Nothing here
    </p>
    {% endif %}

  </div>

{% endblock content %}

courses/templates/main/detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>My Courses</title>
<link rel="stylesheet" href="{% static 'course.css' %}">
{% endblock meta %}

{% block content %}
  <div id="titleDetail">
    <div id="backButton">
      <a class="btn btn-outline" href="{% url 'courses:index' %}" role="button">
        back
      </a>
    </div>
    <p id="courseName">
      {{ course.name }}
    </p>
    <hr width="95%">
  </div>

  <div id="listDetail">
    <p>
        {{ course.teacher }}
    </p>
    <p>
        {{ course.credits }} sks
    </p>
    <p>
        {{ course.year }}
    </p>
    <p>
        {{ course.room }}
    </p>
    <p>
        {{ course.desc }}
    </p>
  </div>

{% endblock content %}